import { pgTable, serial, integer, text, numeric, timestamp, jsonb } from "drizzle-orm/pg-core";

export const ewayBillsTable = pgTable("eway_bills", {
  id: serial("id").primaryKey(),
  businessId: integer("business_id").notNull(),
  ewbNo: text("ewb_no"),
  ewbDate: text("ewb_date"),
  validUpto: text("valid_upto"),
  status: text("status").notNull().default("draft"),
  supplyType: text("supply_type").notNull().default("O"),
  subSupplyType: text("sub_supply_type").notNull().default("1"),
  docType: text("doc_type").notNull().default("INV"),
  docNo: text("doc_no").notNull(),
  docDate: text("doc_date").notNull(),
  fromGstin: text("from_gstin"),
  fromTrdName: text("from_trd_name"),
  fromAddr1: text("from_addr1"),
  fromCity: text("from_city"),
  fromState: text("from_state"),
  fromPincode: text("from_pincode"),
  toGstin: text("to_gstin"),
  toTrdName: text("to_trd_name"),
  toAddr1: text("to_addr1"),
  toCity: text("to_city"),
  toState: text("to_state"),
  toPincode: text("to_pincode"),
  transMode: text("trans_mode").notNull().default("1"),
  transDistance: text("trans_distance"),
  transporterName: text("transporter_name"),
  transporterId: text("transporter_id"),
  transDocNo: text("trans_doc_no"),
  transDocDate: text("trans_doc_date"),
  vehicleNo: text("vehicle_no"),
  vehicleType: text("vehicle_type").notNull().default("R"),
  totalValue: numeric("total_value", { precision: 15, scale: 2 }).notNull().default("0"),
  cgstValue: numeric("cgst_value", { precision: 15, scale: 2 }).notNull().default("0"),
  sgstValue: numeric("sgst_value", { precision: 15, scale: 2 }).notNull().default("0"),
  igstValue: numeric("igst_value", { precision: 15, scale: 2 }).notNull().default("0"),
  totalInvValue: numeric("total_inv_value", { precision: 15, scale: 2 }).notNull().default("0"),
  items: jsonb("items").notNull().default([]),
  invoiceId: integer("invoice_id"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
});

export type EwayBill = typeof ewayBillsTable.$inferSelect;
